---
- name: Create or update a rundeck ACL Application Policy
  community.general.rundeck_acl_policy:
    name: "Application_Policy"
    api_version: {{ rundeck_api_version }}
    url: "{{ rundeck_url }}"
    token: "{{ rundeck_token }}"
    state: {{ rundeck_state }}
    project: "{{ project_name }}"
    policy:
      description: Admin Application level access control, applies to creating/deleting projects, admin of user profiles, viewing projects and reading system information.
      context:
        application: 'rundeck'
      for:
        resource:
          - equals:
              kind: project
            allow: [create] # allow create of projects
          - equals:
              kind: system
            allow: [read,enable_executions,disable_executions,admin] # allow read of system info, enable/disable all executions
          - equals:
              kind: system_acl
            allow: [read,create,update,delete,admin] # allow modifying system ACL files
          - equals:
              kind: user
            allow: [admin] # allow modify user profiles
        project:
          - match:
              name: '.*'
            allow: [read,import,export,configure,delete,promote,admin] # allow full access of all projects or use 'admin'
        project_acl:
          - match:
              name: '.*'
            allow: [read,create,update,delete,admin] # allow modifying project-specific ACL files
        storage:
          - allow: [read,create,update,delete] # allow access for /ssh-key/* storage content

      by:
        group: admin
