---
- name: Create or update a rundeck ACL Application Policy for Creating Projects
  community.general.rundeck_acl_policy:
    name: "{{ policy_name }}"
    api_version: {{ rundeck_api_version }}
    url: "{{ rundeck_url }}"
    token: "{{ rundeck_token }}"
    state:  present
    project: "{{ project_name }}"
    policy:
      description: Author level access for project "X"
      context:
        application: 'rundeck'
      for:
        project:
        - equals:
            name: "{{ project_name }}"
          allow:  [read,import,export,configure,delete]
      by:
        group: admin
  tags: author
