---
- name: Include tasks from runner.yml
     include_tasks: runner.yml
     when: "{{ policy_role }}" == "Runner"
     
- name: Include tasks from author.yml
     include_tasks: author.yml
     when: "{{ policy_role }}" == "Author"
     
- name: Include tasks from admin.yml
     include_tasks: admin.yml
     when: "{{ policy_role }}" == "Admin"
     
- name: Include tasks from remove_policy.yml
     include_tasks: remove_policy.yml
     when: "{{ policy_role }}" == "Remove"


     

