---
- name: Include tasks from runner.yml
     include_tasks: runner.yml
     tags: runner
     
- name: Include tasks from author.yml
     include_tasks: author.yml
     tags: author
     
- name: Include tasks from admin.yml
     include_tasks: admin.yml
     tags: admin
     
- name: Include tasks from remove_policy.yml
     include_tasks: remove_policy.yml
     tags: remove
