 - name: Create or update a rundeck ACL Application Policy for ACL files
  community.general.rundeck_acl_policy:
    name: "Application_Policy"
    api_version: {{ rundeck_api_version }}
    url: "{{ rundeck_url }}"
    token: "{{ rundeck_token }}"
    state:  present
    project: "{{ project_name }}"
    policy:
      description: Admin Application level access control, applies to project access
      context:
        application: 'rundeck'
        for:
          project:
          - equals:
              name: "{{ project_name }}"
            allow: [read,import,export,configure,delete,promote,admin] # allow full access of all projects or use 'admin'
      by:
        group: {{ admin_group }}
