- name: Create or update a rundeck ACL Application Policy for reading system info
  community.general.rundeck_acl_policy:
    name: "Application_Policy"
    api_version: {{ rundeck_api_version }}
    url: "{{ rundeck_url }}"
    token: "{{ rundeck_token }}"
    state:  present
    project: "{{ project_name }}"
    policy:
      description: Admin Application level access control, applies to reading system information.
      context:
        application: 'rundeck'
      project:
        storage:
          - allow: [read,create,update,delete] # allow access for /ssh-key/* storage content
    by:
        group: {{ admin_group }}
