---
- name: Create or update a rundeck ACL policy for a rundeck project job
  community.general.rundeck_acl_policy:
    name: "Project_01"
    api_version: {{ rundeck_api_version }}
    url: "{{ rundeck_url }}"
    token: "{{ rundeck_token }}"
    state: present
    project: "{{ project_name }}"
    policy:
      description: Admin project level access control. Applies to resources within a specific project.
      context:
        project: "{{ project_name }}"
      for:
        job:
        - allow: [create,read,update,delete,run,runAs,kill,killAs] # allow create/read/write/delete/run/kill of all jobs
      by:
        group: {{ admin_group }}
